# ... (viene de los pasos anteriores)
  opa:
    name: Analisis de gobernanza (OPA)
    runs-on: ubuntu-latest
    needs: checkov
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: latest

      - name: Run OPA Check
        run: |
          terraform init
          terraform plan -out=tfplan.binary
          terraform show -json tfplan.binary > tfplan.json
          opa exec --decision terraform/analysis/allow --bundle ../opa/ tfplan.json
